## PyTorch Quiz 1 : Tensor 초기화

In [1]:
import torch
import numpy as np

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [2]:
x = torch.empty(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [5]:
x = torch.zeros(2, 5, 3, dtype=torch.float64)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [6]:
x = torch.ones(4, 4, dtype=torch.int)
print(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [7]:
x = torch.rand(3, 3)
print(x)

tensor([[0.6371, 0.5962, 0.6231],
        [0.8672, 0.8954, 0.3548],
        [0.7234, 0.8548, 0.7738]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [9]:
x = torch.tensor([[1, 2, 3],
                [4, 5, 6]])
print(x.ndim)
print(x.shape) 
print(x)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 속성을 물려받은 원소가 0인 새로운 텐서를 만들어보세요. 

In [10]:
x = torch.randn(2, 2)
print(x)

y = torch.zeros_like(x)
print(y)

tensor([[-0.2514, -0.1197],
        [-1.6403,  1.3144]])
tensor([[0., 0.],
        [0., 0.]])
