In [1]:
import torch
print("setting complete.")

setting complete.


### 문제1 : 기본 인덱싱

In [2]:
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# (1) 첫 번째 행의 두 번째 값을 출력하세요.
print(t[0,1])
# (2) 세 번째 행의 첫 번째 값을 출력하세요.
print(t[2,0])

tensor(2)
tensor(7)


### 문제2 : 기본 슬라이싱

In [3]:
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# (1) 첫 번째와 두 번째 행의 모든 값을 추출하세요.
print(t[0:2, :])
# (2) 모든 행의 첫 번째 열을 추출하세요.
print(t[:,0])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 4, 7])


### 문제 3: 음수 인덱싱

In [4]:
t = torch.tensor([1, 2, 3, 4, 5, 6])
# 끝에서 세 번째 값부터 끝까지 추출하세요.
print(t[-3:])

tensor([4, 5, 6])


### 문제 4: 조건에 따른 필터링

In [5]:
t = torch.tensor([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])
# (1) 양수만 추출하세요.
print(t[t > 0])
# (2) 3으로 나누어떨어지는 값만 추출하세요.
print(t[t % 3 == 0])

tensor([1, 3, 5, 7, 9])
tensor([ 3, -6,  9])


### 문제 5: 슬라이싱으로 값 변경


In [6]:
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 두 번째 행의 값을 모두 0으로 변경하세요.
t[1,:] = 0
print(t)

tensor([[1, 2, 3],
        [0, 0, 0],
        [7, 8, 9]])


### 문제 6: 고급 인덱싱

In [ ]:
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# (1) (0, 1), (1, 2), (2, 0) 위치의 값을 추출하세요.
print(t[[0,1,2],[1,2,0]])
# (2) 두 번째 행과 세 번째 행의 첫 번째 열과 세 번째 열 값을 추출하세요.
print(t[1:, [0,2]])


tensor([2, 6, 7])
tensor([[4, 6],
        [7, 9]])


### 문제 7: 특정 범위 슬라이싱

In [8]:
t = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
# 두 번째와 세 번째 행의 두 번째와 세 번째 열을 추출하세요.
print(t[1:3, 1:3])

tensor([[ 6,  7],
        [10, 11]])
