## PyTorch Quiz 2 : 연산

In [1]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [9]:
x = torch.tensor([2, 4, 6])
# print(x)
# print(x+5)
# print(x-3)
x.add_(5)
print(x)
x.sub_(3)
print(x)

tensor([ 7,  9, 11])
tensor([4, 6, 8])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [10]:
# x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
# y = torch.tensor([[4,5,6],[-1,-2,-3],[9,-4,-5]])
x = torch.rand(3,3)
y = torch.rand(3,3)
add = torch.add(x,y)
print(add)
sub = torch.sub(x,y)
print(sub)
mul = torch.mul(x,y)
print(mul)
div = torch.div(x,y)
print(div)

tensor([[1.1509, 1.0044, 1.4016],
        [0.1264, 0.9535, 0.6159],
        [1.1905, 1.3670, 1.4533]])
tensor([[-0.2703,  0.3127,  0.0521],
        [-0.1036,  0.5995, -0.2998],
        [ 0.3188,  0.4591, -0.4299]])
tensor([[0.3128, 0.2278, 0.4905],
        [0.0013, 0.1374, 0.0724],
        [0.3289, 0.4145, 0.4818]])
tensor([[0.6196, 1.9039, 1.0772],
        [0.0994, 4.3870, 0.3452],
        [1.7314, 2.0113, 0.5434]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [4]:
A = torch.tensor([[1,2,3],[4,5,6]])
B = torch.tensor([[7,8],[9,10],[11,12]])
print(torch.matmul(A,B))

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [ ]:
R = torch.tensor([[58,64],[139,154]])
print(R + 10)
print(torch.clamp(R,max=100))

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 68,  74],
        [149, 164]])
tensor([[ 58,  64],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [8]:
M = torch.tensor([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])
print(torch.sum(M, dim=0))

tensor([55, 60, 65, 70, 75])
