# 03. 텐서의 조작

In [1]:
import torch

## 3-1. 인덱싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [ ]:
x = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(x[1,1]) # 5
print(x[2,0]) # 7
print(x[0, :]) # 0번째 행 전체
print(x[:,2]) # 2번째 열 전체
print(x[[0,1,2],[0,1,2]]) # fancy 인덱싱
print(x[x > 5]) # boolean 인덱싱

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [10]:
x = torch.tensor([10,20,30,40,50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])
