# 03. 텐서의 조작

In [1]:
import torch

## 3-1. 인덱싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [ ]:
x = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(x[1,1]) # 5
print(x[2,0]) # 7
print(x[0, :]) # 0번째 행 전체
print(x[:,2]) # 2번째 열 전체
print(x[[0,1,2],[0,1,2]]) # fancy 인덱싱
print(x[x > 5]) # boolean 인덱싱

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [10]:
x = torch.tensor([10,20,30,40,50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


## 3-2. 텐서의 크기, 모양 변경
- `torch.view()` : tensor의 데이터를 그대로 두고 모양만 변경

In [13]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = y.view(5, -1) # -1 → 자동 계산
print(z)

tensor([[ 0.1250, -2.3036, -0.8695,  0.6479, -1.8056],
        [-0.4903,  2.3995, -1.7236, -1.1242, -1.4115],
        [-1.5180,  1.7276, -0.8179, -0.8827, -0.7447],
        [-1.1948,  1.7016, -0.2908,  1.0828,  0.7908]])
tensor([ 0.1250, -2.3036, -0.8695,  0.6479, -1.8056, -0.4903,  2.3995, -1.7236,
        -1.1242, -1.4115, -1.5180,  1.7276, -0.8179, -0.8827, -0.7447, -1.1948,
         1.7016, -0.2908,  1.0828,  0.7908])
tensor([[ 0.1250, -2.3036, -0.8695,  0.6479],
        [-1.8056, -0.4903,  2.3995, -1.7236],
        [-1.1242, -1.4115, -1.5180,  1.7276],
        [-0.8179, -0.8827, -0.7447, -1.1948],
        [ 1.7016, -0.2908,  1.0828,  0.7908]])


## 3-3. 텐서의 숫자값 얻기
- `tensor.item()` 
    - 스칼라 값 하나만 존재해야 사용 가능
    - Tensor → Python 숫자 변환용

In [16]:
x = torch.rand(1)
print(x)
print(x[0])
print(x.item())

tensor([0.2598])
tensor(0.2598)
0.25979453325271606


## 3-4. 차원 축소 및 증가

### 차원 축소(제거)
- `torch.squeeze()` : 크기가 1인 차원을 제거함

In [17]:
t = torch.rand(3, 1, 3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.7877, 0.8053, 0.8836]],

        [[0.2520, 0.2190, 0.0957]],

        [[0.1294, 0.4941, 0.4299]]])
torch.Size([3, 1, 3])
tensor([[0.7877, 0.8053, 0.8836],
        [0.2520, 0.2190, 0.0957],
        [0.1294, 0.4941, 0.4299]])
torch.Size([3, 3])


### 차원 증가(생성)
- `torch.unsqueeze()` : dim 설정에 따라 차원을 증가시킴
    - dim은 하나의 차원이 추가되는 인덱스

In [21]:
t = torch.rand(3,3,3)
# print(t)
print(t.shape)

# 0 가장 상위 차원 → 3 가장 하위 차원
ts1 = torch.unsqueeze(t, dim=0)
# print(ts1)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
# print(ts2)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim=2)
# print(ts3)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim=3)
# print(ts4)
print(ts4.shape)

torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


## 3-5. 텐서간 결합

- `torch.stack()` : 동일한 형식의 텐서를 새롭게 그룹화 함 → 새로운 차원 생성됨

In [23]:
x = torch.tensor([1,4])
y = torch.tensor([2,5])
z = torch.tensor([3,6])

result = torch.stack([x,y,z])
print(result)

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
result2 = torch.stack([a,b])
print(result2)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- `torch.cat()` : 데이터를 하나의 텐서로 병합 → 새로운 차원 생성X
- dim은 행렬이 맞아야 하나로 합칠 수 있음

In [25]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[7,8],[9,10]])
result = torch.cat((a,b), dim=1)
print(result)

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


## 3-6. 텐서 나누기

- `torch.chunk` : 텐서를 지정한 개수에 따라 나눔
    - 나누어 떨어지지 않는 경우 → 마지막 조각의 크기가 달라짐
    - dim=0이 기본값

In [30]:
t = torch.rand(3,7)
print(t)

t1, t2, t3 = torch.chunk(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.9869, 0.3160, 0.8602, 0.7713, 0.9008, 0.4960, 0.1267],
        [0.4956, 0.0652, 0.6160, 0.6888, 0.9972, 0.1573, 0.0482],
        [0.0488, 0.0377, 0.0225, 0.3123, 0.1423, 0.7112, 0.5142]])
tensor([[0.9869, 0.3160, 0.8602],
        [0.4956, 0.0652, 0.6160],
        [0.0488, 0.0377, 0.0225]])
tensor([[0.7713, 0.9008, 0.4960],
        [0.6888, 0.9972, 0.1573],
        [0.3123, 0.1423, 0.7112]])
tensor([[0.1267],
        [0.0482],
        [0.5142]])


- `torch.split()` : 지정한 사이즈에 따라 나눔
    - 나누어 떨어지지 않는 경우 → 마지막 조각의 크기가 달라짐

In [4]:
t = torch.rand(3,7)
print(t)

t1, t2, t3 = torch.split(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.7295, 0.0524, 0.4063, 0.2344, 0.8328, 0.3856, 0.8509],
        [0.4597, 0.2995, 0.3623, 0.5772, 0.2994, 0.0413, 0.8787],
        [0.6753, 0.4883, 0.1115, 0.4166, 0.9363, 0.5861, 0.6973]])
tensor([[0.7295, 0.0524, 0.4063],
        [0.4597, 0.2995, 0.3623],
        [0.6753, 0.4883, 0.1115]])
tensor([[0.2344, 0.8328, 0.3856],
        [0.5772, 0.2994, 0.0413],
        [0.4166, 0.9363, 0.5861]])
tensor([[0.8509],
        [0.8787],
        [0.6973]])


In [3]:
t = torch.rand(3,7)
print(t)

# 쪼갤 열의 개수 지정
t1, t2, t3 = torch.split(t, [2,3,2], dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.6815, 0.3317, 0.6326, 0.1085, 0.0389, 0.6436, 0.5825],
        [0.9454, 0.9317, 0.4317, 0.6690, 0.3488, 0.5894, 0.7432],
        [0.3178, 0.5676, 0.4294, 0.4648, 0.6920, 0.4179, 0.0093]])
tensor([[0.6815, 0.3317],
        [0.9454, 0.9317],
        [0.3178, 0.5676]])
tensor([[0.6326, 0.1085, 0.0389],
        [0.4317, 0.6690, 0.3488],
        [0.4294, 0.4648, 0.6920]])
tensor([[0.6436, 0.5825],
        [0.5894, 0.7432],
        [0.4179, 0.0093]])
