# 09. Autograd(자동 미분)
- Pytorch는 Tensor의 모든 연산에 대해 자동 미분이 가능함
- 자동 미분은 역전파에 활용됨
- `requires_grad` : Tensor의 속성으로, True로 설정해야 자동미분이 가능
- `tnesor.backward()` : 미분 실행
- `tensro.grad` : 미분값을 확인할 수 있는 속성

In [1]:
import torch

In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
# print(y)
print("미분전 :", x.grad) # `PowBackward0`는 제곱 연산의 미분을 계산해줄 backward 함수

# y.backward() # 미분 실행
# print("미분후 :", x.grad)

z = 3 * y
print(z) # `MulBackward0`는 곱셈 연산의 미분을 계산해주는 backward 함수

z.backward() # 미분 실행
print("z 미분후 :", x.grad)

미분전 : None
tensor([3.], grad_fn=<MulBackward0>)
z 미분후 : tensor([6.])
None


C:\Users\jk316\AppData\Local\Temp\ipykernel_27548\3162218631.py:14: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(y.grad)


In [ ]:
x = torch.tensor([1.], requires_grad=True)
a = x ** 2
b = a + 1
c = b ** 2
c.backward()
print(x.grad)
result = x.grad.detach() # detach : 연산과 결과값을 분리, 연산 그래프에서 분리해서 gradient 계산 안 하게 하는 함수
print(result.requires_grad)
print(result.item())

tensor([8.])
False
8.0


In [18]:
# 다변수 함수 미분
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([3.], requires_grad=True)
z = 2*(x**2) + y**2
print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([11.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([6.])


In [ ]:
# with torch.no_grad():
# grad_fn을 계산하고 싶지 않을 때 사용
# ➡️ 모델 훈련 후 test data를가지고 평가할 때 사용

x = torch.tensor([1.], requires_grad=True)
with torch.no_grad():
    y = x**2
    print(x.requires_grad)
    print(y)
    
print(x.requires_grad)
# y = x**2
y.backward() # with 구문 안쪽의 y로 미분 시도시 에러, with문 안에는 미분 준비 안되어 있음

True
tensor([1.])
True
